### ISSUE TITLE
Star Polygon

### ISSUE THREAD

**Issue by mafagoncalves** [mafagoncalves/PARIAula12b-Equipa1#2]

**Comment by rubendfcosta** [comment]
@miguelriemoliveira quando escrevo  **git commit -m "terminado"** o terminal devolve-me o seguinte erro.

> No ramo master
> Your branch is up to date with 'origin/master'.
> 
> Changes not staged for commit:
> 	modified:   ../src/auxcallbacks.c
> 	modified:   ../src/callbacks.c
> 
> nenhuma modificação adicionada à submissão
>

**Comment by miguelriemoliveira** [comment]
pelo caminho que aparece aqui 

> modified: ../src/auxcallbacks.c
> modified: ../src/callbacks.c

parece que você está a correr o github da pasta errada?

**Comment by miguelriemoliveira** [comment]
está a executar o comando da raiz do repositório?

**Comment by rubendfcosta** [comment]
Já fiz push da minha parte!
